version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: npm-check-updates
    versions:
    - 11.4.1
    - 11.5.1
    - 11.5.3
    - 4.1.2
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
    - 8.2.0
  - dependency-name: dependency-cruiser
    versions:
    - 9.25.0
    - 9.25.1
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
    - 7.23.2
  - dependency-name: eslint-config-google
    versions:
    - 0.14.0
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 2.5.1
  - dependency-name: eslint-config-clickwithclark
    versions:
    - 1.1.5
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: acorn
    versions:
    - 7.4.1
